### ISSUE TITLE
Which memoization library to use?

### ISSUE THREAD

**Issue by mizlan** [exercism/haskell#1108]
I can't seem to use any memoization library when running Exercism tests, stackage or not...

I tried:
- chimera
- memoize
- fastmemo

There are probably more but I don't know how to find them all. What's the recommended solution for this? Get by without memoizing? For reference, I am working on the Change problem, whose most immediate (and imo straightforward) solution is to use a recursive DP algorithm and incorporate memoization.

**Comment by mizlan** [comment]
Oh and I forgot to mention: the reason why I cannot use these libraries is because of #1006

**Comment by MatthijsBlom** [comment]
> I can't seem to use any memoization library when running Exercism tests, [&hellip;]

This is caused by no memoization libraries being listed as [dependencies of the test runner](https://github.com/exercism/haskell-test-runner/blob/main/pre-compiled/package.yaml). This cannot be fixed other than by arguing that one should be added and sending an patch.

> What's the recommended solution for this?

In a local environment, you can use any dependencies you like. Only on the Exercism servers will compilation fail.

> Get by without memoizing?

Yes, or rolling your own. Maybe you can lazily generate intermediate results into a data structure, and then to get the answer index into that data structure? Incidentally, that is how MemoTrie does it.

**Comment by mizlan** [comment]
Understood. Rolling my own seems sufficient for probably all cases here. Thanks!
