### ISSUE TITLE
Intention behind not updating a Queen Attack test

### ISSUE THREAD

**Issue by MatthijsBlom** [exercism/haskell#1136]
Looking to apply a patch from problem-specifications in order to eliminate a false positive, I encountered the following.

https://github.com/exercism/haskell/blob/322ee64f32dbaf097951513312c4ba3ff7c03bab/exercises/practice/queen-attack/.meta/tests.toml#L40-L44

@petertseng Do you remember why this was decided? I cannot find documented reasoning.

**Comment by petertseng** [comment]
I must have had a different idea of what constitutes "different diagonals" than the submitter of https://github.com/exercism/problem-specifications/pull/1504. If we look at (2, 2) in relation to the four different values it's being compared against: `(0, 4)`, `(3, 1)`, `(1, 1)`, `(5, 5)`, we have: `(LT, GT)`, `(GT, LT)`, `(LT, LT)`, `(GT, GT)`. But if it were changed to `(1, 7)` vs `(0, 6)`, well that's a `(LT, LT)` and then we don't have a `(GT, GT)` case, and that doesn't make sense to me.

But I see from reading https://github.com/exercism/problem-specifications/pull/1504 this allows a different problem, because the important part isn't really their relative positions; it's about testing two different rising/falling diagonals. However I think if the Haskell track takes this case, we should use `(0, 6)` vs `(1, 7)` instead of `(1, 7)` vs `(0, 6)`, so that we still have a `(GT, GT)` case.

**Comment by petertseng** [comment]
(For those who aren't following along, the mathematics behind it is that a rising diagonal is expressed as `y = x + b`, and a falling diagonal is expressed as `y = -x + b`)

**Comment by petertseng** [comment]
Honestly though that means that one of the two cases `(2, 2), (0, 4)` or `(2, 2), (3, 1)` should be changed too, since they are obviously going to be testing the same diagonal as well (since they both contain `(2, 2)`. That should also get submitted to problem-specifications.
