### ISSUE TITLE
Exercise Grains: square function is not useful

### ISSUE THREAD

**Issue by MazeChaZer** [exercism/haskell#646]
The exercise Grains requires you to implement the `square` function in order to pass all the tests. I believe using this square function is not a very good solution and requiring it distracts from better solutions to the problem. Here are two solutions that I believe are better than the example solution given in https://github.com/exercism/haskell/blob/5dcf977c53ca30ddb18cdee3f5c78cc331eeb815/exercises/grains/examples/success-standard/src/Grains.hs and don't require a `square` function:

```haskell
total :: Integer
total = sum . take 64 . iterate (* 2) $ 1
```

```haskell
total :: Integer
total = 2 ^ 64 - 1
```

Additionally, I find the return type of `Maybe Integer` strange. Why is this function supposed to defined only on the interval of [1,64]? If it was a 10×10 checker board, the function wouldn't work anymore. In the `total` function you have to use `fromJust` anyway to unpack it, so why use `Maybe` in the first place?

I suggest removing the `square` function from the exercise boilerplate and tests.

**Comment by rbasso** [comment]
Hi, @MazeChaZer!

> Here are two solutions that I believe are better than the example solution given...

We never cared too much about the example solutions. They are just used to automatically test the exercises in Travis-CI.

> Why is this function supposed to defined only on the interval of [1,64]?

Because a chessboard has exactly 64 squares, and that is the exercise's thematic background. I agree that it could be more general, but that would sacrifice the theme.

> Additionally, I find the return type of `Maybe Integer` strange.

I think we strive to avoid [partial functions](https://wiki.haskell.org/Partial_functions) in Haskell, and it is idiomatic to use `Maybe` or `Either` to signal invalid inputs when we are unable to limit that at type-level.

Anyway, I believe it is important to expose students to `Maybe` as early as possible in the track, because it is everywhere in Haskell. Also, along with lists, being comfortable with both help in building an intuitive understanding of *functors*, *applicative functors* and *monads*.

> In the `total` function you have to use `fromJust` anyway to unpack it, so why use `Maybe` in the first place?

Great question! 😄 

If you are annoyed about using `fromJust`, your feeling is right. 👍

I took me a while to understand the root of this problem. Let's see the prerequisite:

1. Given a square, return the number of grains in it, **if the input is valid**.

```haskell
square :: Int -> Maybe Integer
```

2.  Return the to total number of grains in the board.

```haskell
total :: Integer
```

You are right in that there is no way to write total with `square` without dealing with `Maybe` in an ugly way. But you don't need to use `square`!

Both `square` and `total` can be written using another function that can only receive valid squares.

I wrote [this solution](http://exercism.io/submissions/9551431c043a4a68a6a27b9f8f0c1fc6) based on that idea, trying to mimic the problem's specification (using recursion) while avoiding ugly hacks. 

IMHO, both, `square` and `total`, have sensible types.

It is up to the student to choose how to deal with `total`:
- Repeat the code from `square`.
- Write an independent formula.
- Create a datatype representing a squares in the chessboard.
- Input the constant directly.

**Comment by MazeChaZer** [comment]
Thanks for the extensive answer :)

I think I read the exercise README to quickly, I assumed that the only task was to calculate the total number of grains. Now I see that calculating the number of grains on a certain field is its own task.

> We never cared too much about the example solutions. They are just used to automatically test the exercises in Travis-CI.

I don't really mind the example solution neither, just wanted to illustrate that using the `square` function to calculate the total might not be so straightforward.

> I think we strive to avoid partial functions in Haskell, and it is idiomatic to use Maybe or Either to signal invalid inputs when we are unable to limit that at type-level.
>
> Anyway, I believe it is important to expose students to Maybe as early as possible in the track, because it is everywhere in Haskell. Also, along with lists, being comfortable with both help in building an intuitive understanding of functors, applicative functors and monads.

Sure, `Maybe` makes sense here then. I like that the Haskell track uses `Maybe` for functions that might fail.

So after all it seems that I was just confused with the structure of the exercise. I thought I was supposed to use the `square` function, which at first guided me away from better solutions.

**Comment by rbasso** [comment]
If there isn't anything else to be done here, @MazeChaZer, I guess it would be great if you could close the issue. It isn't always clear from the maintainers point-of-view if an issue is solved, so that he/she can close it and focus on other issues.

**Comment by MazeChaZer** [comment]
Sure, closing
