### ISSUE TITLE
package.yaml error in stack version 1.6.5

### ISSUE THREAD

**Issue by siddharthasahu** [exercism/haskell#672]
I'm getting this error in newly downloaded exercises:
`package.yaml: Error while parsing $.library.dependencies - expected Array, Object, or String, encountered Null`

That is because everything under `library -> dependencies` in `package.yaml` is commented out. Commenting out  `dependencies` itself solves the issue.

**Comment by petertseng** [comment]
I was able to reproduce this on my computer, but could not reproduce on Travis. Why is that?

I don't want to delay the fix; the fix should happen as soon as possible. Within that constraint (solving problem as soon as possible), the commit message that explains the problem should be as precise as possible as to when the problem occurs. Looking at logs, most updates of https://github.com/exercism/trackler/tree/master/tracks happen at around 14:00 my time, so about 13 hours from now. So there are at least 13 hours to investigate and get a fix in.

I see that on Travis, `stack --version` says:

Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0

I see that in contrast, I have hpack-0.27.0. So sometime between hpack 0.20.0 and 0.27.0 .

**Comment by petertseng** [comment]
Since I'm not able to reliably acquire `stack` compiled against any other versions of `hpack`, "sometime between `hpack` 0.20.0 and 0.27.0" is probably the most precise designation I can provide. 

 could read the source code to figure out, but I cannot do that reliably because https://github.com/sol/hpack/blob/0.20.0/src/Hpack/Dependency.hs#L59 already would have rejected `Null` (why JSON instead of YAML?), so it was something surrounding it. The relevant change may not even be in `hpack`.
