### ISSUE TITLE
Unable to run `stack test` on Ubuntu 16.04

### ISSUE THREAD

**Issue by cmccandless** [exercism/haskell#683]
Environment Info:
```bash
cmccandless@********:~/exercism/haskell/strain$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
cmccandless@********:~/exercism/haskell/strain$ uname --all
Linux ******** 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Problem Encountered:
```bash
cmccandless@********:~/exercism/haskell/strain$ stack test
/home/cmccandless/exercism/haskell/bob/package.yaml: Error while parsing $.library.dependencies - expected Array, Object, or String, encountered Null
```

This occurs for any exercise I try.

**Comment by petertseng** [comment]
But I thought after https://github.com/exercism/haskell/pull/680 that no `package.yaml` will have `$.library.dependencies` anymore, therefore there should be no attempt (and therefore no error) parsing it.

Did I misunderstand the situation? Does the `package.yaml` in fact contain a `$.library.dependencies`?

Please excuse me if I ask any questions that appear overly naive; in my case they are necessary since this issue is not reproducible on Travis (which uses Ubuntu 14.04 instead of 16.04) nor my machine (which also doesn't use Ubuntu 16.04)

**Comment by cmccandless** [comment]
I see... I keep all of my solutions to End problems in a repo, and was setting up my environ for the first time under Linux. I neglected to check if there was any significant updates to the Haskell before with the latest version of stack. I will update my personal files and everything should work then.
