### ISSUE TITLE
AesonException when running Hello World

### ISSUE THREAD

**Issue by radwane-h** [exercism/haskell#687]
Hey,

I am experiencing an exception with the hello world code. Here is the complete error message
stack setup
Downloaded lts-11.1 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""

Here is stack --version
Version 1.5.1 x86_64 hpack-0.17.1

And it seems to work when added --nix --resolver lts-9.14 as suggested here 
https://stackoverflow.com/questions/47962377/cannot-build-a-hello-world-program-with-stack-because-of-flag-bytestring-lt-0-1

**Comment by petertseng** [comment]
By using a search engine (that will remain unnamed), I found https://github.com/tfausak/cassava/commit/1f66af2cdf5657eec6adf022f06eaebe21bb7442 which explains this issue.

It is found via https://github.com/commercialhaskell/stack/blob/master/ChangeLog.md#v161 that 1.6.1 is necessary.

It will not feel right to me to keep the maximum Stackage LTS release of this repository to https://www.stackage.org/lts-9.21 (Note that https://www.stackage.org/lts-9.22 does not exist, while https://www.stackage.org/lts-10.1 has the concerned versoin of cassava). The reason is that that would keep on old GHC versions and package versions, while I prefer to continue to receive improvements to GHC and packages.

My request to you: Please confirm that you can upgrade Stack to >= 1.6.1 and that it fixed this issue, and close this issue, or confirm that you cannot upgrade, with any explanations and considerations why the upgrade is not possible, and any proposed solutions. For example, it may be that you will have to continue using the resolver you named.

**Comment by petertseng** [comment]
EBWODP:

> that 1.6.1 is necessary

That Stack 1.6.1 is necessary.

**Comment by radwane-h** [comment]
Thanks for you answer I actually tried to upgrade stack but apparently I didn't notice that the new install wasn't in the path... not familiar with haskell tools yet. But once I get to have a newer version it worked just well. Thx
