### ISSUE TITLE
All extra exercises have become locked

### ISSUE THREAD

**Issue by ktoth** [exercism/haskell#721]
Hi, I have completed the core track and doing the extra exercises now, however as of today none of the exercises are unlocked anymore, except for the ones in progress/completed and an odd one I have checked out earlier from farther down the page.

On the web page they show up with the lock icon, in the CLI I get the `Error: You have not unlocked this exercise` message.

Maybe this issue has something to do with commit #691?

**Comment by tiniuclx** [comment]
I am also having a similar issue: only the exercises unlocked by Hello World are truly unlocked, all the others are locked.

**Comment by tiniuclx** [comment]
Finishing another core exercise did unlock its side exercises, but all the others remain locked. Perhaps the database which stores what exercises were unlocked by which student was not updated?

**Comment by tiniuclx** [comment]
I have been looking at the source of the website, and I think that [this file](https://github.com/exercism/website/blob/master/app/controllers/my/solutions_controller.rb#L9) can help explain some of the behaviour experienced by myself and ktoth.

The script implies that a solution object is created for each user whenever they look at an exercise (I haven't yet found the code that does this though). However, the code linked above does contain the logic for when a solution object is created.

Such a solution object is created if the user `may_unlock_execise?`. The reason why @ktoth can see the exercise he checked out earlier is because the solution object for that particular exercise was created before #691. I can also replicate that exact same behaviour by clicking on an exercise I looked at in the past.

All of this leads me to believe that when an user unlocks an exercise, the fact that they have done so is recorded in a database. The database is checked by `may_unlock_exercise?` and fails to return a solution because the deployment of commit #691 has marked those exercises as locked.

The definition of [`may_unlock_exercise`](https://github.com/exercism/website/blob/master/app/models/exercise.rb#L44) also leads me to believe that this is the case: it checks whether a solution corresponding to the current user exists.

Please take all of this with a grain of salt: I have little webdev experience and no Ruby experience, all I want is to get to the bottom of this and get this fixed as quickly as possible :)

**Comment by tiniuclx** [comment]
I just had an idea for a temporary workaround: the root of the problem is that exercises that should be unlocked are locked. The most straightforward way to unlock such exercises is to switch to independent and look at every exercise that should be unlocked. That should update the database accordingly, and since the exercises should be unlocked in the first place, they will remain so after you switch back to mentored mode.

I will try this and update you with my findings.

**Comment by tiniuclx** [comment]
Success! It turns out it's even simpler than I thought! Switching to independent mode unlocks all exercises, and switching back locks only those exercises that aren't unlocked by the core track. 

## Workaround ## 
1. Switch to independent mode by clicking the button at the side of the page and going through the dialog menu: 
![image](https://user-images.githubusercontent.com/24615474/45458105-00fd4180-b6ea-11e8-80e2-2d8d32d730cc.png)

1. Switch back to mentored mode by clicking the button at the bottom of the page and going through a similar dialog:
![image](https://user-images.githubusercontent.com/24615474/45458150-32760d00-b6ea-11e8-9966-63d21ca6671d.png)

1. All the correct exercises should now be unlocked!

**Comment by tiniuclx** [comment]
For a more permanent fix: the `Switch to Mentored Mode` [updates a single solution](https://github.com/exercism/website/blob/9b38dd3382f3284c48056fb414eff2dfb7c703a4/app/services/switch_solution_to_mentored_mode.rb#L9). 

To fix this problem for all users, the highlighted function should be called for all solutions on the Haskell track, albeit without changing its `independent_mode` parameter. For this, you would likely need someone with administration access to the track, or to the website itself, and you might have to translate it into an MySQL query in order to apply it to the database.

I would like to remind you once more to take what I am saying with a grain of salt and think through the consequences of my proposed fix before doing something that affects all 4,362 students on the Haskell track :)

**Comment by sshine** [comment]
Excellent debugging, @tiniuclx.

I'll respond later today.

**Comment by petertseng** [comment]
What is the status of this issue?

Yesterday I found that the only exercises that were unlocked for me were those exercises that branch off of a particular one core exercise. I think I either only was able to access `hello-world`'s side exercises or I was only able to access `leap`'s side exercises, but I don't remember which statement is true (or if neither statement is true).

Particularly telling was the fact that there are four free-standing exercises and none of them were unlocked for me (but they should always be unlocked, right?)

```
[free] nucleotide-count
[free] grade-school
[free] isogram
[free] diamond
```

However, I am no longer in this state as of today. Today the only exercise I have locked is `acronym`. You might ask why only `acronym` but I would not know.

What is the suggestion action that this track should take, based on this issue? I notice that it's been pointed out that it's because of #691. Is the call to action to revert #691? Or is it something else?

**Comment by tiniuclx** [comment]
I don't think reverting #691 is the way to go. While it will probably unlock all side exercises for everybody, we would run into this issue again whenever we tried to define side exercises.

I believe that fixing this issue for students on this track would involve refreshing / recalculating the unlock status of all Haskell solutions stored in the database.

@ktoth, are all your side exercises still locked?

**Comment by ktoth** [comment]
First of all, thanks for all the debugging and fixing efforts.

Yes, the exercises are still locked.

**Comment by iHiD** [comment]
I'm running a script to fix this. Please give it a couple of hours, then let me know if there are still issues. Thanks.

**Comment by iHiD** [comment]
(For future reference, feel free to cc me or @exercism/website into any problems that relate to problems with how things are working on the website :))

**Comment by tiniuclx** [comment]
Awesome, thanks a lot! I will keep it in mind for the future.

**Comment by ktoth** [comment]
Now everything works perfectly for me. Thank you all for the quick fix!
