### ISSUE TITLE
Clock exercise doesn't test `show`

### ISSUE THREAD

**Issue by swalladge** [exercism/haskell#747]
The Clock exercise description calls for implementing an instance of `Show`, but only a function `toString` is tested. Should the description or test be updated?

**Comment by petertseng** [comment]
In summary, the better course of action is probably **to remove `toString` and instead have the tests test `show`**.

### Rationale

**Using `show` seems closest to how usual Haskell would be written**. http://book.realworldhaskell.org/read/using-typeclasses.html#typeclasses.wellknown.show tells about `Show` giving a representation that would be parseable using `Read`. It seems that the representation of `hh:mm` does indeed fit that requirement.

If the assumption "Using `show` seems closest to how usual Haskell would be written" is instead false, then the recommendation should instead be to remove the mention of `Show` from the requirements (and instead to continue testing `toString`.

### Recommendation

A person who wants to close this issue would take the following steps:

* Remove mentions of `toString` from https://github.com/exercism/haskell/blob/master/exercises/clock/.meta/hints.md and https://github.com/exercism/haskell/blob/master/exercises/clock/README.md
* change the `toString` stub in https://github.com/exercism/haskell/blob/master/exercises/clock/src/Clock.hs to a stub of `show` (probably with an `instance Show Clock where`)
* change the `toString` in https://github.com/exercism/haskell/blob/master/exercises/clock/examples/success-standard/src/Clock.hs to `show`, possibly also removing the `deriving Show` in the process.
* change `toString` in https://github.com/exercism/haskell/blob/master/exercises/clock/test/Tests.hs to `show`
* Use a word in https://help.github.com/articles/closing-issues-using-keywords/ to indicate that this issue is to be closed

### History

Reading this section **is not necessary to inform any decisions on this issue**; it only serves to explain how things got this way.

In the initial addition of Clock to this repo in https://github.com/exercism/haskell/pull/12 , the example solution had `deriving Show`, but the tests did not use it, since the tests were using `toString`. The instructions to the student did *not* ask for Show at this point in time.

In https://github.com/exercism/haskell/pull/200 when a stub was added to Clock, the instruction to have a `Show` instance was added at this time, perhaps based on the fact that the example solution had a `Show` instance.

**Comment by NobbZ** [comment]
Isn't `Show` necessary for the testsuite? Also `Show` usually creates a string that I can copy and paste literally into a Haskell source file.

This is not true for the string generated by the `toString` function in the example.

Therefore I vote for not changing anything.

**Comment by petertseng** [comment]
> Isn't `Show` necessary for the testsuite?

I found that this was not true - I was able to remove `Show` with no problems. Since a `Clock` is never used directly in a `should` (or similarly used), it is not necessary for a `Clock` to be a `Show`.

> `Show` usually creates a string that I can copy and paste literally into a Haskell source file.

If this is truly a requirement, then it is true that we do not want to use `Show` here. I have not yet been able to find literature that tells me this is a requirement. All I have found as a requirement in http://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html#v:show and http://learnyouahaskell.com/making-our-own-types-and-typeclasses is that you can `read` what you `show`. I hope to hear about any literature showing the requirement.

**Comment by NobbZ** [comment]
I never have seen any documentation stating that.

I've only seen this as best practise through Haskell sources I looked at, it is common practice in the prelude (eg. `Map`, instead of printing something that is similar to maps in other languages you get `fromList [("key", "value")]`).

Also my FP teacher at university always said so. And I had a small chat with him already this morning. He had no sources I could link to available as well, but always derived his opinion from a sentence in the description of derived `Show` instances and thought it is best to do the same for manually implemented instances (least surprise and stuff):

> [derived `Show` has following properties:]
> * The result of `show` is a syntactically correct Haskell expression containing only constants, […]

**Comment by jeeger** [comment]
Yes, something like `show "Hans"` in ghci returns `"\"Hans\""`. This isn't really required for the clock example.
