### ISSUE TITLE
Conform file layout in track

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#781]
According to exercism/meta#15 there is a file layout that appears to be a standard.

The Haskell track appears to not follow it (although it's not the only track that does not).

Would it make sense to change the file layout to achieve a higher degree of track conformity?

**Comment by sshine** [comment]
We don't have a `.meta` directory in which all files that are not distributed to the student are located.

**Comment by petertseng** [comment]
Partially true. Breakdown of which parts are true and which not:

> We don't have a `.meta` directory

False for all exercises in the below list, and true for all others:

```
$ ls -1 exercises/*/.meta/*                           (11-26 20:07)
exercises/allergies/.meta/hints.md
exercises/alphametics/.meta/hints.md
exercises/anagram/.meta/hints.md
exercises/bank-account/.meta/hints.md
exercises/beer-song/.meta/hints.md
exercises/binary-search-tree/.meta/hints.md
exercises/bowling/.meta/hints.md
exercises/clock/.meta/DONT-TEST-STUB
exercises/clock/.meta/hints.md
exercises/custom-set/.meta/hints.md
exercises/food-chain/.meta/hints.md
exercises/forth/.meta/hints.md
exercises/go-counting/.meta/hints.md
exercises/grade-school/.meta/hints.md
exercises/hello-world/.meta/hints.md
exercises/house/.meta/hints.md
exercises/leap/.meta/hints.md
exercises/linked-list/.meta/hints.md
exercises/matrix/.meta/hints.md
exercises/meetup/.meta/hints.md
exercises/octal/.meta/hints.md
exercises/palindrome-products/.meta/hints.md
exercises/parallel-letter-frequency/.meta/hints.md
exercises/queen-attack/.meta/hints.md
exercises/robot-name/.meta/hints.md
exercises/robot-simulator/.meta/hints.md
exercises/roman-numerals/.meta/hints.md
exercises/series/.meta/hints.md
exercises/sgf-parsing/.meta/hints.md
exercises/simple-linked-list/.meta/hints.md
exercises/space-age/.meta/hints.md
exercises/sublist/.meta/hints.md
exercises/trinary/.meta/hints.md
exercises/word-count/.meta/hints.md
exercises/wordy/.meta/hints.md
```

> in which all files that are not distributed to the student are located.

True, because of examples. But examples are so important that I really don't want to put them in a directory whose name starts with a `.` because such directories are so inconvenient for tab-completion. I will defend this position if there is ever an attempt to establish a standard that examples should go in such a directory.

**Comment by petertseng** [comment]
So it is true that we don't conform to the statement as stated ("a file is not served to the student if and only if it is in the `.meta` directory"). 

However, I believe the following:

* That statement does not represent any standard that tracks are being asked to adhere to
* It would make my experience as a maintainer worse (and have precisely zero effect on students) if we moved examples to `.meta` in order to adhere to that statement

Thus, I have no interest in adhering to it.

**Comment by sshine** [comment]
I'm happy you have an opinion, and I agree that it makes finding examples is hard, even in the GitHub website that does not hide .dirs and makes skipping empty directories in one jump. So if we aim for examples to have any educational purpose for the curious student, they should remain where they are.

Now I know.
