### ISSUE TITLE
Pangram: Add non-basic characters in the test suite

### ISSUE THREAD

**Issue by Sir4ur0n** [exercism/haskell#824]
I see many students filtering using `Char.isLetter` , then removing duplicates, and then checking the size is 26.

I think this would be nice to add other characters (e.g. `'字'`) which are letters (`Char.isLetter '字' == True`) in the test suite to make them realize this is not a good enough function for pangram.

Any opinion? If you agree I can submit a PR.

**Comment by petertseng** [comment]
Although adding such a case would be in contravention of the Exercism-wide decision of https://github.com/exercism/problem-specifications/issues/428, individual tracks are allowed to contravene Exercism-wide decisions if those involved (maintainers, proposer, others contributors, etc.) decide it is a good idea.

Since I don't have a specific recommendation in either direction, I leave it to the interested parties to determine if it is a good idea.

**Comment by petertseng** [comment]
EBWODP:

> decision of exercism/problem-specifications#428

the message should be edited to explain that decision so that one does not have to click through to understand it:

The exercism-wide decision to only have ASCII unless the exercise is specifically about dealing with multi-byte encodings

**Comment by Sir4ur0n** [comment]
I wasn't aware of this ASCII restriction, thanks for pointing it out, I guess I will stop using the example of Chinese letters then 😅

**Comment by sshine** [comment]
I think this test case is very good. Since Exercism has a policy against non-ASCII canonical tests, I think we should create a Haskell-specific test case. We may want to use a letter that people are not in doubt about being a letter, e.g. `'Ã'` and not e.g. [`'ˀ'` (glottal stop)](https://stackoverflow.com/questions/52643395/string-contains-only-the-alphabet-in-haskell). :-P

**Comment by sshine** [comment]
The class of errors you describe are false positives.

But our test suite should also describe false negatives.

1. False positives:

   ```haskell
   isPangram :: String -> Bool
   isPangram = (== 26) . length . nub . map toLower . filter isLetter
   ```

   succeeds for `isPangram (['a'..'y'] ++ "æ")` when it should fail.

2. False negatives:

   ```haskell
   isPangram :: String -> Bool
   isPangram = (== ['a'..'z']) . sort . nub . map toLower . filter isAlpha
   ```

   fails for `isPangram (['a'..'z'] ++ "æøå")` when it should succeed.

Eventually, once exercism/problem-specifications#1518 is resolved, we may be interested in discussing in the problem-specifications repo whether to change the ASCII policy so that Unicode tests can be allowed, but are always listed as optional because they're Unicode.

In the meantime I would prefer that these two tests are added in the Haskell track.

@Sir4ur0n: Would you be interested in submitting a PR that adds these two to the Haskell track?
