### ISSUE TITLE
Question:  is the waiting time really so long ?

### ISSUE THREAD

**Issue by rwobben** [exercism/haskell#833]
hello, 

IM trying to learn  haskell  and one fo the things to practice haskell are the challenges in this repo.
So I solve the first one (leap)  and see this : 

``` 
 The median waiting time for mentoring on this exercise is 11 days. 
``` 

must a beginner really wait 11 days or more before he/she sees a mentor answer.
I think a lot of beginners are then gone and leave haskell for another language.

Regards,

Roelof

**Comment by sshine** [comment]
Hi @rwobben 

You are right, 11 days between each core exercise is not satisfactory. For the Haskell track, the exercise queue grows faster than the volunteer mentors give feedback. Let me show some statistics for the last few weeks:

* Week 33: 81 solutions submitted for mentoring, 65 solutions mentored. Queue length: 189.
* Week 32: 50 solutions submitted for mentoring, 19 solutions mentored. Queue length: 206.
* Week 31: 64 solutions submitted for mentoring, 28 solutions mentored. Queue length: 195.
* Week 30: 72 solutions submitted for mentoring, 16 solutions mentored. Queue length: 197.

As you can see, we do have bursts, most likely performed by individuals. I've once or twice given feedback to as much as 80-100 solutions per week, but my average these weeks is 10-20 and on some weeks 0.

There are no publicly available statistics (and so not available to me either) on how many mentors perform this task, but my guess is that for the Haskell track, we have 1-3 semi-active mentors. It could be that we have more, and that every mentor on average is less active, but my anecdotal experience tells me that the average mentor has some very busy sprints for some weeks or months, and then become less active until someone else takes over with another sprint.

The page that lists submissions to core exercises is ordered by time, so mentors can always see which submissions have waited the longest. We have a general strategy of keeping all core exercises low, but especially the first three exercises.

It happened once this year that we emptied the queue, and it took three mentors who were all periodically active for two weeks. This would approximately be sufficient for the track's current popularity, although it will become more popular if it becomes known that feedback times are only a couple of days.

One strategy could be to shorten the core track to a point where our current mentor efforts are sufficient: That is, not offer mentoring in more exercises than we have human resources for. That would decrease the total potential learning instead of stretching this across months. Another strategy could be to disable feedback for non-core exercises: We *almost never* get around to giving feedback to them anyways, so enabling feedback to them seems dishonest.

As the lack of mentor resources is not just a problem for the Haskell track, the Exercism project is also looking into how to resolve this resource problem in more general ways. In particular, (1) how to make mentoring more sociable and appealing since we're talking about hours of volunteer work per week. And (2) how to automate feedback for early exercises using custom code analysers. We don't have an active submission code analyser project for Haskell, but I've been doing some research into making this with HLint: Either entirely using .hlint.yml, or partially using an extended version of it, since its source code provides an excellent framework.

If you have other ideas, feel free to share them here, or I can point you to the general project discussion concerning these sad statistics. (Another sad fact: The average waiting time for *one* submission on the Rust track used to be **2 months**.)

**Comment by sshine** [comment]
Another project-wide effort is to change the mentoring model so that students get the same mentor through the entire core track. This way, students are perhaps more likely to complete the track in a reasonable amount of time, and fewer students might be able to get any feedback. Maybe it will be a mixture of the current model and this all-the-way model, I'm not really sure.

Still, having a chance at getting timely feedback on 10 exercises sounds better than certainly getting untimely feedback until one eventually tires out.

**Comment by rwobben** [comment]
I do not have a solution at hand. I just wondered about it.

**Comment by sshine** [comment]
Then in order to address your question, "*must a beginner really wait 11 days or more*", I would say that the answer is no, and that there are several possible solutions that could reduce that number, but that they require consideration and implementation.

**Comment by rwobben** [comment]
I agree with that

**Comment by sshine** [comment]
I'll close this issue, then, in favor of a project-wide effort to address this problem, or until a concrete, track-specific proposal is made. For example, some tracks have had luck attracting mentors by advertising Exercism on various subreddits.
