### ISSUE TITLE
Porting zipper with recursion-schemes

### ISSUE THREAD

**Issue by zhujinxuan** [exercism/haskell#851]
Hi, I find the [zipper](https://github.com/exercism/haskell/tree/master/exercises/zipper) is not implemented yet.  I can do it with recursion-schemes (because it is fun).

I can make a PR once you think it is good.

Cheers,
Jinxuan Zhu

**Comment by petertseng** [comment]
I wasn't sure what this means. Since you linked to https://github.com/exercism/haskell/tree/master/exercises/zipper, it is clear to see that the zipper exercise is already implemented. Was there a different exercise you were thinking of implementing?

**Comment by zhujinxuan** [comment]
@petertseng Sorry, I made a mistake on the purpose of the project.  I thought it was about giving solutions instead of giving exercises.


Sorry, my mistake.  I will close this issue.

**Comment by sshine** [comment]
@zhujinxuan: The example solutions that inhabit this repository mainly show that a solution is possible and serves to validate the test suite. Sometimes there are multiple examples for a single exercise, but mainly when the exercise can be solved with different configurations.

E.g. if a solution can be solved with `Data.Text` rather than `String`, we'd like to know that changes to the test suite does not break overloading between those options. When different solutions are encapsulated entirely by the interface, they're better off in the "community solutions" on the website (which needs an overhaul to be truly useful).

You are very welcome to port something else;

```
$ jq -c --argjson canonical \
        "$(cd ~/exercism/problem-specifications/exercises \
           && printf '%s\0' * | jq -R 'sub("\u0000$"; "") | split("\u0000")')" \
    '$canonical - (.exercises | map(.slug))' config.json
["affine-cipher","book-store","circular-buffer","counter","darts","diffie-hellman",
"dot-dsl","error-handling","flatten-array","grep","hangman","high-scores","knapsack",
"ledger","markdown","micro-blog","nucleotide-codons","paasio","point-mutations",
"rational-numbers","react","rectangles","resistor-color","resistor-color-trio",
"rest-api","reverse-string","satellite","scale-generator","tournament","tree-building",
"two-bucket","two-fer","variable-length-quantity","word-search"]
```

(`tree-building` is a work in progress in #835, though; I have several drafts for some of them that I haven't gotten around to finishing, so I won't let that discourage you from picking freely among the rest.)

**Comment by Javran** [comment]
Just a side note that I was trying to find a list of problems not yet ported and wrote a script to do that, may as well share it here: https://gist.github.com/Javran/ac02edfe611b8dd88e9aae0699f77eff

**Comment by sshine** [comment]
That's cool. :) The jq script that does the same above is from the [Exercism jq Cookbook](https://github.com/exercism/exercism/issues/5055). It was later supplemented by @SleeplessByte's [track tracking page](https://tracks.exercism.io/), but this no longer shows non-implemented practice exercises. It now shows but rather shows the [migration progress](https://tracks.exercism.io/haskell/v3/launch) for Exercism v3 in an attempt to motivate those tasks being fulfilled first.

**Comment by Javran** [comment]
Thanks for the link to cookbook and tracker! I do appreciate monitoring and live visualization whenever they show up :)

**Comment by SleeplessByte** [comment]
(track tracking page on the dashboard is back up! :D)

**Comment by SleeplessByte** [comment]
https://tracks.exercism.io/haskell/main/unimplemented

Hard refresh if you get a white page / error. You have a broken cached version.
