### ISSUE TITLE
package.yaml much behind on some exercises

### ISSUE THREAD

**Issue by chevinbrown** [exercism/haskell#864]
I've had trouble running `stack test` on the hello-world exercise with ghc `8.6.5` and `8.8.1` (which is all I tried before finding `8.4.4` worked). 

The installation guide may need to specify a ghc version.

**Comment by sshine** [comment]
Hi @chevinbrown, and thanks for reporting any difficulties with the track.

`stack test` is supposed to look in stack.yaml for a `resolver: lts-...` and use the GHC version for that [Stackage.org LTS version](https://www.stackage.org/). Incidentally, I saw your issue just as I was going to comment on #846, where @petertseng bumps the LTS to 14.7, corresponding to GHC 8.6, on this exact matter:

Because of a behavior in the current website, students don't get updated copies of handout files unless the test file specifically was touched. That means, for example for hello-world, that the stack.yaml students get is two years old, because this was when test/Tests.hs was last changed.

The effect of some exercises using GHC 8.2, some 8.4, and some 8.6 is pretty bad: It potentially means that students will download new GHC versions when they advance between single exercises.

A simple solution could be to mass update all test/Tests.hs files with a linebreak.

**Comment by chevinbrown** [comment]
Makes sense. This is pretty unattainable for _students_ to understand, IMO. 
I've never done any haskell myself, so I had to hunt these things down _without any knowledge of the ecosystem_. 😕 

As a student, I feel like a "recommended version" could be a great starting point. I can see this being a barrier to entry for less experienced or less persistent students.

Would it be helpful for me to submit a PR that ensures consistency across all exercises?

**Comment by chevinbrown** [comment]
I did just update `hello-world` `stack.yaml` to `resolver: lts-14.8` with ghc `8.6.5` and we're back on track.

**Comment by sshine** [comment]
> "recommended version"

I'm not sure what you mean, exactly. Maybe you could elaborate? The track currently recommends (and really necessitates) the use of Stack (since no .cabal file is provided independently of package.yaml), and the "Guides" section on the track instructs how to compile and test code.

> Would it be helpful for me to submit a PR that ensures consistency across all exercises?

Let's wait a short while. I'd like to investigate the cost of fixing the bug rather than working around it.

**Comment by sshine** [comment]
> Would it be helpful for me to submit a PR that ensures consistency across all exercises?

I don't have the capacity to fix the bug, so let's aim for a workaround.

Since we're going through all this trouble, we might as well copy #846 and bump LTS to 14.9.

The necessary steps for every exercise `$e`:
1. Add a linebreak to the end of `$e/test/Tests.hs` to force update.
2. Bump the 4th (serial) component of `version: ...` in `$e/package.yaml`.
3. Set `resolver: lts-14.9` in `$e/stack.yaml`.

Just as in #846, it is neccessary to complete a line in the commit message that reads:

```
I have confirmed that no README check is needed
```

to avoid a certain CI check, since we're affecting all exercises.

I've assigned you to the task, @chevinbrown. Let me know if you need any assistance.

**Comment by petertseng** [comment]
The requirement that the test file changed is unfortunate. I wish https://github.com/exercism/website/blob/45147d7a1c34f16ef4bc41b07ed9790667521420/app/models/concerns/solution_base.rb#L53-L62 were able to be aware of other files.

We can't even use the solution "Add a newline, then immediately remove it in another commit" since it appears this just checks whether the content of the test file is the same.

And what are we going to do when stack.yaml is updated again? Go and remove all the newlines that were added to the test files? In that case, students who got the exercise *two* updates ago will now will remain out of date, since their test file now has no net change.

So, I won't object to the workaround if it solves an immediate need, but I warn strongly that we will find even this workaround to be untenable in the future.

**Comment by petertseng** [comment]
By the way, I didn't change the `version` when I changed the `stack.yaml` previously (in any instances). I don't remember why. I think my reasoning was "tests didn't change"? So I don't see that as a requirement of changing `stack.yaml`.

**Comment by sshine** [comment]
> And what are we going to do when stack.yaml is updated again?
> Go and remove all the newlines that were added to the test files?

That was my thought, yes.

> In that case, students who got the exercise two updates ago will now will remain out of date, since their test file now has no net change.

The merge code you link to compares git commit hashes, not diffs, so I don't see how this will be a problem.

> So I don't see *[changing the `version`]* as a requirement of changing `stack.yaml`.

No, that's true, I'm being unclear. Bumping version is only necessary because we touch test/Tests.hs.

I was suggesting that since we're going to spam the track repo, we might as well bump the LTS in the process. This is not strictly necessary, though, since lts-14.7 is very decent. We probably don't even really need to bump LTS again until lts-15.x covers GHC 8.8.x.

Maybe if we get track-specific exercise that uses some very state-of-the-art library. For example: Hedgehog 1.0 generators only got their MonadGen instances for StateT 4 days ago. (They were present in pre-1.0, but weren't added back after some refactoring.) Which is hypothetical, and we still have the option of `extra-deps`.

I've removed bumping the LTS from @chevinbrown's to-do list.

> I warn strongly that we will find even this workaround to be untenable in the future.

I've outlined a general solution in exercism/exercism#5052.

It also addresses the situation where students upload a modified `package.yaml` and are thus prevented from receiving updates to `package.yaml` for that exercise. This is, after all, a common thing those I give feedback when I encourage they use e.g. `Data.Map`, `Data.Set`, `Data.Text`.

It seems that @iHiD is prioritizing other aspects (see his response), so let's see what happens in time. We don't have automated tests or linters running after `exercism submit` yet, so we don't yet experience package conflicts when students submit a solution that does not compile because of missing packages. (It is more common than not that people `import Data.Text` without uploading package.yaml, so we will have either one problem or the other.)

**Comment by petertseng** [comment]
> The merge code you link to compares git commit hashes, not diffs, so I don't see how this will be a problem.

that is not what I see.

```
    latest_head = Git::ExercismRepo.current_head(exercise.track.repo_url)
    return true if git_sha == latest_head
    test_suite == Git::Exercise.new(exercise, git_slug, latest_head).test_suite
```

True if the git sha is the same.
If the git sha is not the same, it checks whether the test suites are the same.

**Comment by petertseng** [comment]
I'll need to read https://github.com/exercism/website/blob/7983b2b6cc6a05f95090561201696cf7b9c01f00/app/models/git/exercise_reader.rb (used by https://github.com/exercism/website/blob/7983b2b6cc6a05f95090561201696cf7b9c01f00/app/models/git/exercise.rb) to determine what is meant by "test suites are the same" though.

**Comment by petertseng** [comment]
https://github.com/exercism/website/blob/b1646c2723d0562677f512c2d00f30e9e4efd119/app/models/git/repo_base.rb#L25-L32 says:

```ruby
    blob = lookup(oid)
    return default if blob.nil?
    blob.text
```

I look at https://www.rubydoc.info/github/libgit2/rugged/Rugged/Repository#lookup-instance_method which says `lookup` gives a subclass of https://www.rubydoc.info/github/libgit2/rugged/Rugged/Object. This is a bit speculative, but I'm going to look in https://www.rubydoc.info/github/libgit2/rugged/Rugged/Blob given the name of `blob = lookup(oid)`. Then I see that https://www.rubydoc.info/github/libgit2/rugged/Rugged/Blob#text-instance_method returns a string.

So, if there were no mistakes in this line of reasoning, then "test suites are the same" just compares the text content of the test suite. So if there were no mistakes, that would affirm what I said:

> In that case, students who got the exercise two updates ago will now will remain out of date, since their test file now has no net change.

**Comment by sshine** [comment]
Thanks for putting in the research.

In that case, any consistent solution boils down to including a unique checksum in each test file.

Since changing the test file necessitates bumping the version number, maybe the best checksum we have is the version number from package.yaml. Having it in two places is annoying, but if we're going to require that each change to any handout file ⇒ test file is changed to something unique, then perhaps the version number is the least annoying unique identifier.

Alternatives:
- A UUID: Harder to verify that it's unique across track repo history.
- The SHA1 of `master`: Easy to verify, but does not commute rebasing.

As for making this convenient, we could put a git pre-commit hook in the track repo, make CI use this hook and, in case of failure, print a message in the CI log on why this failed and how to enable the hook that is available in the track repo. This may lower the barrier for entry slightly. I imagine one of these (and each contributor can feel free to use whichever they prefer, since hooks are set up locally):

1. A pre-commit hook that fails if the test file wasn't uniquely updated.
2. A pre-commit hook that will inject the unique update into the test file.

**Comment by sshine** [comment]
Alternatively, we can modify this unique ID periodically and accept that PRs that affect only non-test files for an exercise don't get rolled out immediately. This solution preserves the barrier for entry, but we have something to keep track of; maybe GitHub Actions can be of use here.

**Comment by sshine** [comment]
> I didn't like putting the exercise version in the test file because then it would be duplicated

I don't like that it's duplicated, either.

> if we just removed the version from package.yaml and had the test file be the only place that contains it? There's no real reason the test version has to be in package.yaml

That's an option, but I think package.yaml is a really good place to put it because it actually has a `version: ...` attribute.

> I'm OK with some other indicative string that is placed in the test file as well

As I understand it, we've established current possibilities:

1. Move the version to test/Tests.hs
2. Duplicate the version in package.yaml and test/Tests.hs
3. Keep the version in package.yaml, use other unique identifier in test/Tests.hs

For (3) we'd technically only need to update the checksum if any handout file but test/Tests.hs is updated. But all three workarounds have drawbacks (outlined in previous messages) that I'm not happy about.

> I wish that the track could specify that an update to package.yaml also allows the student to see the "Update me" button, not just the tests, but that functionality requires a larger design.

Yes, that'd be ideal.

@petertseng: How do you feel about doing a one-off
```bash
echo -e "\n-- $(sha1sum test/Tests.hs | awk '{print $1}')" >> test/Tests.hs
```
for each exercise and bump version from x.y.z.i to x.y.z.(i+1)" and I can try and look at the file merging algorithm in the website before we need to do this again? The net benefit is that students will only download GHC 8.6.

**Comment by sshine** [comment]
> some other indicative string

Are you suggesting that it should be a meaningful string, or would you be okay with something like a SHA1 checksum?

**Comment by petertseng** [comment]
> >  some other indicative string
>
> Are you suggesting that it should be a meaningful string, or would you be okay with something like a SHA1 checksum?

Ah, I guess I misspoke and the choice of word "indicative" was not indicative of my desired meaning. A meaningless string that can freely be changed at any time would also be fine (but remember it is desirable to never use the same meaningless string more than once).

Therefore, regarding the suggested

> `echo -e "\n-- $(sha1sum test/Tests.hs | awk '{print $1}')" >> test/Tests.hs`

Yup, sure.

I will also throw in "put only the last version number component (serial component) in the test file, leaving the full version number in package.yaml", but that is also prone to potentially being forgotten about.

We just have to make our pick of one of multiple equally bad solutions. It is a shame, but apparently that is life. So we should just pick one.

**Comment by sshine** [comment]
If we go with prepending the line `-- $(sha1sum test/Tests.hs)` of the test file itself, then this will work as a seed for the same kind of update at a later time, since the previous checksum becomes salt in the next one. The Haskell track's very own blockchain!

@petertseng: Can I ask @chevinbrown to perform this task?

As a second step, if we need to do this again, we could devise a script that calculates a new checksum, uses the existing checksum as part of its input (by effect of its presence in the file), and replaces the existing checksum with the newly calculated one. But let's defer this to a different issue, as we may want to discuss it separately.

**Comment by petertseng** [comment]
> Can I ask @chevinbrown to perform this task?

First I will say yes, then I will give a general rule that can hopefully be used to generate future "yes"es and remove the need for questions.

Well, I already said yes to the task, and generally I am completely agnostic to who actually performs a task. So if I said yes to a task and not specifically designate that a specific person should do it, I'd like for it to be safe to assume I would say yes to any person doing it.

> the previous checksum becomes salt in the next one

That is indeed a necessary property to ensure that the file content differs in some way. Another possible way we can ensure uniqueness is to use the current time as part of the input to the hash in some way. But my suggestion is useless because the hash's presence in the file already provides this property; my suggestion is not to be used.
