### ISSUE TITLE
Hackage links in Markdown files don't necessarily match Stack LTS

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#868]
When a `.meta/hints.md` file or some other Markdown file in the track repo links to e.g. https://hackage.haskell.org/package/text-1.2.3.1/docs/Data-Text.html there is no guarantee that this is the version of the package that the student ends up using when adding `- text` in package.yaml.

The current solution, to include the latest version at the time of writing (or whatever version one ended up copy-pasting; Google isn't always friendly), has the drawback that the API link becomes outdated over time in every Markdown file across the track repo.

An alternative solution, which is to remove the version info in those links, e.g. https://hackage.haskell.org/package/text/docs/Data-Text.html, such that it redirects to the latest version of the package. This still does not guarantee that it is the version of the package that the student ends up using, since we may be behind on updating `stack.yaml`. In addition, a newer version of the package may have deleted a module, causing a 404. This is, however, unlikely as long as we stick to recommending packages with stable APIs.

Still, this alternative means that we only need to keep track of Stack LTS package versions in `stack.yaml` and will not have to think about which packages got bumped between Stack LTS releases.

If we can reach a track policy on this matter, it means that many Markdown files can be updated to have their specific version information stripped.

*(The golden solution is to match package versions of all packages linked to in Markdown files against a relevant Stack LTS -- the package's or some constant Stack LTS version assumed in the track repo for links not specifically tied to one exercise. This, however, seems like a lot of work.)*

**Comment by petertseng** [comment]
The perfect solution does seem like a lot of work. Of the alternatives I can currently think of, it seems that not having a version in the links (thus using https://hackage.haskell.org/package/text/docs/Data-Text.html) would be the lesser problem, but I will live if we choose some other solution.

To help us reach an understanding of the current spread of the situation, I took a look at existing links.

```

$ git grep --only-matching -h 'hackage.haskell.org/package/[^/]*/' | sort | uniq 
hackage.haskell.org/package/array/
hackage.haskell.org/package/base/
hackage.haskell.org/package/QuickCheck-2.12.6.1/
hackage.haskell.org/package/text/
hackage.haskell.org/package/text-1.2.3.1/
```

Well, that command might even be useful were someone to implement the perfect solution one day.

I would like to mention another opportunity for confusion, other than a 404, so we understand what we get into if we choose to omit version numbers:

A student visits link `package/foo` without a version and gets redirected to the latest version (call it 1.1) and sees "ah, this function `bar` would be useful in my solution, I will use it!" but hark! It turns out `bar` was only added in `foo` 1.1 but the track is using `foo` 1.0. Come to think of it, I am unsure how likely this situation is.
