### ISSUE TITLE
Matrix exercise is under-specified by test suite

### ISSUE THREAD

**Issue by SiriusStarr** [exercism/haskell#881]
The only test for the `reshape` function in the test suite reshapes to a symmetric matrix:
```
reshape (2, 2) (intMatrix "1 2 3 4") `shouldBe` intMatrix "1 2\n3 4"
```
As such, there is nothing to prevent someone from writing a function that inverts the desired output dimensions  (possibly speaking from experience here.  >_>).  Either a case with non-equal rows/columns should be added or (probably better) the property that `shape . reshape dimension $ matrix == dimension` for all valid `dimension`/`matrix`.

Edit:  Hit send early.

**Comment by sshine** [comment]
That sounds about right.

Thanks for noticing and reporting back.

Matrix is a large-ish side exercise and so does not get a lot of attention from mentors or track maintainers.

You are welcome to submit a pull request.

Whether you test this property using a single unit test or write a QuickCheck property is entirely up to you.

Normally I'd ask you to also submit a pull request to the problem-specifications repo which governs the common unit tests across language tracks, but the repo is currently closed due to maintenance, so I think the better choice is to make it a track-specific test.

Note to myself: Make a list of unit tests we intend to port upstream eventually.

**Comment by SiriusStarr** [comment]
PR up; please let me know if it can be improved, as I am not hugely experienced with Haskell.
