### ISSUE TITLE
nucleotide-count: awkward to require filling out sparse `Map` datastructure

### ISSUE THREAD

**Issue by jitwit** [exercism/haskell#902]
The tests reject solutions that don't fill out returned map with `0` for missing nucleotides.  @sshine and I were talking about this while I was doing the track exercises and we thought it might be nice to remove this pain point. Some possible approaches:

* Have solution return a function `Nucleotide -> Int` which leaves the student free to choose whatever representation.
* Rewrite the success predicate `matchesMap` to be more liberal.
* Use a dense structure like `array` instead of `map`.
* Something else?

**Comment by sshine** [comment]
To confirm, I think it would be a good idea to modify the Nucleotide Count exercise so that solutions with a sparse representation are also correct. If we were to change the exercise stub into

```haskell
data Nucleotide = A | C | G | T deriving (Eq, Ord, Show)

nucleotideCounts :: String -> Nucleotide -> Either String Int
nucleotideCounts xs x = error "You need to implement this function."
```

then we would eliminate the necessity for even using a `Data.Map`, which makes the interface more abstract, but we would also lose on the goal of getting acquainted with the `containers` package. There might be a subtle point in still using a `Data.Map` internally if the function is partially applied and called multiple times in its last argument, but this could be added to the mentoring notes for the exercise.

In this interpretation we would continue to conform to [canonical tests](https://github.com/exercism/problem-specifications/blob/master/exercises/nucleotide-count/canonical-data.json) and we would only need to modify [`matchesMap`](https://github.com/exercism/haskell/blob/master/exercises/nucleotide-count/test/Tests.hs) slightly. Also, we might like to use `Data.Map.findWithDefault`. A mentor might also concede that `(Int, Int, Int, Int)` is a sufficient internal representation. Let's leave the mentor notes as a separate concern.

**Comment by sshine** [comment]
Feel free to submit a PR that amends this.

**Comment by jitwit** [comment]
Just opened one with what I thought would be the easiest to implement (`findWithDefault`). Happy to experiment with some of the other approaches as well

**Comment by jitwit** [comment]
```
nucleotideCounts = fmap (fromListWith (+).map (,1)).traverse (readEither.pure)
```
now works
