### ISSUE TITLE
complex-numbers: Test file error: No instance for (Eq (Complex Float))

### ISSUE THREAD

**Issue by countersoda** [exercism/haskell#904]
The side exercise "Complex Numbers" has an error in the Tests.hs file. I am not able to compile this file.

**Comment by NobbZ** [comment]
Can you please elaborate on what error you see?

The exercises are tested regularly on CI to make sure that they can be delivered safely to students.

Perhaps also tell us how you run the tests, what version of `stack`, `haskell`, `cabal`, etc are involved.

Also please tell us what operating system you use and if there are any containerisation and/or virtualisation layers involved.

**Comment by sshine** [comment]
An important detail: What `version` is in package.yaml?

Because it might be the most recent one because of #864.

**Comment by countersoda** [comment]
I am using a windows os. The package.yaml version is 1.3.0.6. I am running the tests through Visual Studio Code. When compiling the test I get an error saying: 

"No instance for (Eq (Complex Float))
        arising from a use of `shouldBe'
    * In the first argument of `on', namely `shouldBe'
      In the expression: shouldBe `on` roundComplex 2
      In an equation for `shouldBeAround':
          shouldBeAround = shouldBe `on` roundComplex 2
   |
45 |   shouldBeAround = shouldBe `on` roundComplex 2"

**Comment by NobbZ** [comment]
How does VScode run the tests?

Does the same error appear when you do `stack test` in a terminal?

Also which versions of `stack`, `haskell`, `cabal`, etc are involved?

**Comment by countersoda** [comment]
VScode runs the test by entering the complex numbers file and calling "stack test". I also did run it on the terminal and I got the same result. 
haskell version: 8.6.5
stack version: 1.9.3

**Comment by countersoda** [comment]
cabal version: 2.4.1.0
What else do you need the version of?

**Comment by petertseng** [comment]
I think that regardless of any versions, it is going to be the case that `shouldBe` will require its argument to be `Eq`. After all, hspec would not be able to assert that two things were equal unless they were equatable. Okay.

By default as provided to the student, we say in https://github.com/exercism/haskell/blob/b5de2edb900db8581d4ab6dcd446a74fd472a11e/exercises/complex-numbers/src/ComplexNumbers.hs#L17 that `data Complex a = Dummy deriving(Eq, Show)`, which we expect to make `Complex Float` an `Eq`, because `Float` is `Eq` (as seen on http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Eq.html). Compare the two GHCI sessions.

With deriving:

```haskell
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
Prelude> data Complex a = Dummy deriving Eq
Prelude> Dummy == Dummy
True
```

Without:

```haskell
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
Prelude> data Complex a = Dummy
Prelude> Dummy == Dummy

<interactive>:2:1: error:
    • No instance for (Eq (Complex a0)) arising from a use of ‘==’
    • In the expression: Dummy == Dummy
      In an equation for ‘it’: it = Dummy == Dummy
```

So to solve this issue we should consider some possibilities such as: is there some version of `base` where `Float` is not `Eq`, or the `deriving` there has unexpected behaviour.

**Comment by petertseng** [comment]
EBWODP: Used an implementation of `Complex` that references `a` instead of Dummy, separated out possibilities into clearer bullet points, added another possibility.

I think that regardless of any versions, it is going to be the case that `shouldBe` will require its argument to be `Eq`. After all, hspec would not be able to assert that two things were equal unless they were equatable. Okay.

By default as provided to the student, we say in https://github.com/exercism/haskell/blob/b5de2edb900db8581d4ab6dcd446a74fd472a11e/exercises/complex-numbers/src/ComplexNumbers.hs#L17 that `data Complex a = Dummy deriving(Eq, Show)`, which we expect to make `Complex Float` an `Eq`, because `Float` is `Eq` (as seen on http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Eq.html). Compare the two GHCI sessions with an example definition of `Complex`.

With deriving:

```haskell
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
Prelude> data Complex a = C a deriving Eq
Prelude> C (5.0 :: Float) == C (5.0 :: Float)
True
```

Without:

```haskell
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
Prelude> data Complex a = C a
Prelude> C (5.0 :: Float) == C (5.0 :: Float)

<interactive>:2:1: error:
    • No instance for (Eq (Complex Float)) arising from a use of ‘==’
    • In the expression: C (5.0 :: Float) == C (5.0 :: Float)
      In an equation for ‘it’: it = C (5.0 :: Float) == C (5.0 :: Float)
```

So to solve this issue we should consider some possibilities such as:

* is there some version of `base` where `Float` is not `Eq`
* is there some version of the compiler where the `deriving` there has unexpected behaviour
* is there some problem in Exercism, where the `deriving Eq` part did not get delivered to the student. Note that the history of https://github.com/exercism/haskell/commits/master/exercises/complex-numbers/src/ComplexNumbers.hs tells us `deriving Eq` has always been there, so that problem would be more than "used wrong version of repository history".

**Comment by countersoda** [comment]
I see. I derived Eq. It worked. Thank you
