### ISSUE TITLE
I am getting access violation error when i try to run 'stack test'

### ISSUE THREAD

**Issue by stackBlock** [exercism/haskell#920]
stack test works fine on my other haskell builds but when i try to run stack test on any of the exercises I have tried from exercism, I get this error:

---------------------------------------

λ stack test
Linking C:\\sr\\setup-exe-cache\\x86_64-windows\\tmp-Cabal-simple_Z6RU0evB_3.0.1.0_ghc-8.8.3.exe ...

Access violation in generated code when writing 0x0

 Attempting to reconstruct a stack trace...        

   Frame        Code address
 * 0x461da80    0x37f7b66 C:\Users\antho\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\bin\ghc.exe+0x33f7b66
 * 0x461da88    0x3277bb9 C:\Users\antho\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\bin\ghc.exe+0x2e77bb9
 * 0x461da90    0x3
 * 0x461da98    0x7846ce1
 * 0x461daa0    0x3d80c90 C:\Users\antho\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\bin\ghc.exe+0x3980c90
 * 0x461daa8    0x6978c50

--  While building simple Setup.hs using:
      C:\Users\antho\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\bin\ghc-8.8.3.EXE -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-3.0.1.0 C:\sr\setup-exe-src\setup-Z6RU0evB.hs C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs -o C:\sr\setup-exe-cache\x86_64-windows\tmp-Cabal-simple_Z6RU0evB_3.0.1.0_ghc-8.8.3.exe
    Process exited with code: ExitFailure 11

-------------------------------------------

I would like to continue with the problems but I can't test anything. Do you know how to fix this error?

Thank you,
Anthony

**Comment by sshine** [comment]
Hi Anthony / @stackBlock 

I typed "Haskell stack Access violation in generated code when writing" into Google and got some results:

https://github.com/haskell/haskell-ide-engine/issues/1779#issuecomment-635167944

So this is a bug that relates to GHC 8.8.3 on Windows.

Since we updated all exercises to use GHC 8.8.4 in #926 two days ago, perhaps you can tell me if re-downloading an exercise works? (Alternatively, try and download any new exercise and see if it contains `resolver: lts-16.21` in stack.yaml.)

---

If not,

One quick fix is to change `resolver: lts-...` to `resolver: lts-14.27`, since that is equivalent to GHC 8.6.5 which does not have this problem. I don't think there are any exercises that won't immediately work on GHC 8.6.5, since not a lot of exercises were updated since GHC 8.8 was released.

You'd need to apply that hack to every single exercise, so that might be a little tedious.

Alternatively, consider working with Haskell inside a virtual machine running Ubuntu.

I'm going to close this issue for now, but feel free to get back and comment.
