### ISSUE TITLE
Is someone still working on this ? 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/haskell#979]
Hello, 

I wonder if someone is still working on this. Would be a pity if this repo is not ready for version 3.

Regards, 

Roelof

**Comment by petertseng** [comment]
Despite not having resigned as a maintainer for this track yet (as I have for one other track), I can confirm that I have not worked on this track since November 2020. I cannot speak for other maintainers.

**Comment by petertseng** [comment]
CI fixed.

**Comment by petertseng** [comment]
I believe the silence is answer enough on whether anyone is working on this. Because the purpose of the issue is to ask this question, and because we presume the question has been answered (in the negative - nobody is still working on this), the issue has served its purpose and issues that served their purpose can be closed.
